In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler,LabelEncoder
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report
from sklearn.linear_model import LogisticRegression

## Ques 1 ->
### Perform Naive Bayes Classification on the dataset Social_Network_Ads.csv. Use Gender,Age, EstimatedSalary to predict Purchased column value.

In [3]:
df = pd.read_csv('/content/Social_Network_Ads.csv')
df.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [4]:
label_Encode = LabelEncoder()
df['Gender'] = label_Encode.fit_transform(df['Gender'])

In [5]:
df.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510       1   19            19000          0
1  15810944       1   35            20000          0
2  15668575       0   26            43000          0
3  15603246       0   27            57000          0
4  15804002       1   19            76000          0

In [6]:
standard_scaler_cols = ['Age','EstimatedSalary']
min_max_scaler_cols = ['Purchased']

In [7]:
# standard_scaler = StandardScaler()
# df[standard_scaler_cols] = standard_scaler.fit_transform(df[standard_scaler_cols])

min_max_scaler = MinMaxScaler()
df[min_max_scaler_cols] = min_max_scaler.fit_transform(df[min_max_scaler_cols])

In [8]:
X = df[['Gender','Age','EstimatedSalary']]
y = df['Purchased']

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state=42)

In [9]:
model = GaussianNB()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)

In [10]:
print("Model Performance Metrics: ")
print(f"Accuracy : {accuracy:.2f}")
print(f"Precision : {precision:.2f}")
print(f"Recall : {recall:.2f}")
print(f"f1 Score : {f1:.2f}\n")
print(classification_report(y_test,y_pred))
print(conf_matrix)


Model Performance Metrics: 
Accuracy : 0.94
Precision : 0.93
Recall : 0.89
f1 Score : 0.91

              precision    recall  f1-score   support

         0.0       0.94      0.96      0.95        52
         1.0       0.93      0.89      0.91        28

    accuracy                           0.94        80
   macro avg       0.93      0.93      0.93        80
weighted avg       0.94      0.94      0.94        80

[[50  2]
 [ 3 25]]


In [11]:
print("\nPredicated va Actual Outcomes (Test Set) : ")
for actual, predicated in zip(y_test, y_pred):
  print(f" Actual: {actual}, Predicated: {predicated}")


Predicated va Actual Outcomes (Test Set) : 
 Actual: 0.0, Predicated: 1.0
 Actual: 1.0, Predicated: 1.0
 Actual: 0.0, Predicated: 0.0
 Actual: 1.0, Predicated: 1.0
 Actual: 0.0, Predicated: 0.0
 Actual: 0.0, Predicated: 0.0
 Actual: 1.0, Predicated: 1.0
 Actual: 0.0, Predicated: 0.0
 Actual: 0.0, Predicated: 0.0
 Actual: 0.0, Predicated: 0.0
 Actual: 0.0, Predicated: 0.0
 Actual: 1.0, Predicated: 1.0
 Actual: 0.0, Predicated: 0.0
 Actual: 0.0, Predicated: 0.0
 Actual: 0.0, Predicated: 0.0
 Actual: 0.0, Predicated: 0.0
 Actual: 1.0, Predicated: 1.0
 Actual: 0.0, Predicated: 1.0
 Actual: 0.0, Predicated: 0.0
 Actual: 1.0, Predicated: 1.0
 Actual: 0.0, Predicated: 0.0
 Actual: 0.0, Predicated: 0.0
 Actual: 1.0, Predicated: 1.0
 Actual: 1.0, Predicated: 1.0
 Actual: 0.0, Predicated: 0.0
 Actual: 1.0, Predicated: 1.0
 Actual: 0.0, Predicated: 0.0
 Actual: 0.0, Predicated: 0.0
 Actual: 1.0, Predicated: 1.0
 Actual: 0.0, Predicated: 0.0
 Actual: 1.0, Predicated: 0.0
 Actual: 0.0, Predicated:

## Ques 2 ->
### For the above, use logistics regression.

In [12]:
model = LogisticRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)

In [13]:
print("Model Performance Metrics: ")
print(f"Accuracy : {accuracy:.2f}")
print(f"Precision : {precision:.2f}")
print(f"Recall : {recall:.2f}")
print(f"f1 Score : {f1:.2f}\n")
print(classification_report(y_test,y_pred))
print(conf_matrix)

Model Performance Metrics: 
Accuracy : 0.89
Precision : 0.91
Recall : 0.75
f1 Score : 0.82

              precision    recall  f1-score   support

         0.0       0.88      0.96      0.92        52
         1.0       0.91      0.75      0.82        28

    accuracy                           0.89        80
   macro avg       0.90      0.86      0.87        80
weighted avg       0.89      0.89      0.88        80

[[50  2]
 [ 7 21]]


## Ques 3 ->
### Use loan_data.csv dataset. Perform Naive Bayes classification to predict if the customer repays the loan in full (not.fully.paid column). Use all the other columns are features/predictors.

In [14]:
df = pd.read_csv('/content/loan_data.csv')
df.head()

credit.policy             purpose  int.rate  installment  log.annual.inc  \
0              1  debt_consolidation    0.1189       829.10       11.350407   
1              1         credit_card    0.1071       228.22       11.082143   
2              1  debt_consolidation    0.1357       366.86       10.373491   
3              1  debt_consolidation    0.1008       162.34       11.350407   
4              1         credit_card    0.1426       102.92       11.299732   

     dti  fico  days.with.cr.line  revol.bal  revol.util  inq.last.6mths  \
0  19.48   737        5639.958333      28854        52.1               0   
1  14.29   707        2760.000000      33623        76.7               0   
2  11.63   682        4710.000000       3511        25.6               1   
3   8.10   712        2699.958333      33667        73.2               1   
4  14.97   667        4066.000000       4740        39.5               0   

   delinq.2yrs  pub.rec  not.fully.paid  
0            0        0               0  
1            0        0               0  
2            0        0               0  
3            0        0               0  
4            1        0               0

In [15]:
categorical_cols = df.select_dtypes(include=['object']).columns
label_encoder = LabelEncoder()

for col in categorical_cols:
    df[col] = label_encoder.fit_transform(df[col])

X = df.drop(columns=["not.fully.paid"])
y = df["not.fully.paid"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


In [16]:
model = GaussianNB()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)

In [17]:
print("Model Performance Metrics: ")
print(f"Accuracy : {accuracy:.2f}")
print(f"Precision : {precision:.2f}")
print(f"Recall : {recall:.2f}")
print(f"f1 Score : {f1:.2f}\n")
print(classification_report(y_test,y_pred))
print(conf_matrix)

Model Performance Metrics: 
Accuracy : 0.79
Precision : 0.32
Recall : 0.28
f1 Score : 0.30

              precision    recall  f1-score   support

           0       0.87      0.89      0.88      1611
           1       0.32      0.28      0.30       305

    accuracy                           0.79      1916
   macro avg       0.59      0.58      0.59      1916
weighted avg       0.78      0.79      0.78      1916

[[1431  180]
 [ 221   84]]
